### ISSUE TITLE
installation fails on newest ubuntu

### ISSUE THREAD

**Issue by riku2015** [fhats/partify#129]
after running fresh installation of ubuntu 12.04.1 and running installation scripts the partify will not work.

manually running follow command i get:

riku@ubuntu-testi:~$ sudo run_partify
[sudo] password for riku:
Traceback (most recent call last):
  File "/usr/local/bin/run_partify", line 5, in <module>
    pkg_resources.run_script('Partify==0.4', 'run_partify')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Partify-0.4-py2.7.egg/EGG-INFO/scripts/run_partify", line 22, in <module>
    from partify import start
  File "/usr/local/lib/python2.7/dist-packages/Partify-0.4-py2.7.egg/partify/**init**.py", line 30, in <module>
    from partify.config import load_config_from_db
  File "/usr/local/lib/python2.7/dist-packages/Partify-0.4-py2.7.egg/partify/config.py", line 24, in <module>
    from partify.database import db
  File "/usr/local/lib/python2.7/dist-packages/Partify-0.4-py2.7.egg/partify/database.py", line 21, in <module>
    from flaskext.sqlalchemy import SQLAlchemy
ImportError: No module named flaskext.sqlalchemy
riku@ubuntu-testi:~$

**Comment by fhats** [comment]
Hi riku! Thanks for trying out Partify!

I'm travelling at the moment, but I am aware of the issue -- I failed to specify a max version on most of the dependencies for Partify, and consequently some of the packages have gone out of date. I am going to try to publish a hotfix to PyPI next week!

Thanks,
-Fred

**Comment by riku2015** [comment]
Hello, 

I have party now at 6. day   my 30¨s :D heh have invited 130+ persons :) wanna join? heh

anyway i found the problem, here it comes:
edit file
nano  /usr/local/lib/python2.7/dist-packages/Partify-0.4-py2.7.egg/partify/database.py
and change this line:
from flaskext.sqlalchemy import SQLAlchemy
to:
from flask.ext.sqlalchemy import SQLAlchemy

then it works! :) thanks anyway for this great soft!:)

**Comment by fhats** [comment]
Solid! Sounds like a fun party.

I'll still aim to try to fix up the dependencies and/or move forward to a newer version of flask this week.

Thanks for trying out Partify! Let me know how it works for you

**Comment by riku2015** [comment]
Thanks it worked fine, but we haved some issues. we was having like 10+ more guests on system.. well... after 2-3  being same time choosing songs system started lag badly. prosessor 100% (on 2400+ amd) So dunno what to do with that? faster computer??? this cant demand quad processor just for music play lol.. :D so something need to be done about code on gui, alot javascript eats processor power on server and client side.. some optimization i mean :) 
anyway best program ever guests liked alot! only lack of feature about amouth songs guest can be added same time.. :/

**Comment by fhats** [comment]
Heh, I'd be the first to admit that partify needs some optimization work. On the CPU-intensity -- it's likely the round-robin scheduler that causes problems. I noticed a while back that it can get stuck in a nasty edge case where it tries to flip two tracks back and forth forever. I'd be curious to see if you notice problems with a different schedule (maybe first-come first-served?).

And yes, it appears as though the client side could use some work too. I think something in the jQueryUI components tends to eat a lot of cycles (I'm probably misusing a component somewhere).

Now that someone else is using this I guess I should start revisiting some of these bugs :) Glad it (mostly) worked out for you at your party!
