### ISSUE TITLE
Search for an album

### ISSUE THREAD

**Issue by mcclurem** [fhats/partify#37]
I'd like to be able to search for and add an album - ie have albums separated out as a chunk similar to the way itunes calls an "Album List". Perhaps implementation would show the album cover next to the album name and clicking on the album image would add the album as a chunk or clicking on the songs themselves would add them one at a time

**Comment by mcclurem** [comment]
A treeview

**Comment by fhats** [comment]
Good idea. I'm putting this on the wishlist but hopefully when track results come back a little more intelligently it will be easy to do an iTunes-style (and Spotify does it too) view of the albums along with options for the album.
