### ISSUE TITLE
New track sometimes appears twice in party queue

### ISSUE THREAD

**Issue by tobywaite** [fhats/partify#62]
When adding an album's worth of tracks, the first track appeared twice in the party queue. The user listed on one was "Anonymous". The track was not actually in the queue twice, however, as skipping first track moved straight to the second song on the album and did not restart the first song.

I haven't tried to figure out how to reproduce this bug, because I'm a horrible user.

**Comment by fhats** [comment]
Note to self: needs a locking mechanism against the Mopidy update listener and certain endpoints (like add, remove, etc).
